
#debug: true

#spring:
#  main:
#    web-application: reactive

#server:
#  servlet:
#    context-path: /ingestor

logging:
  level:
    root: info

spring:
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
  jackson:
    serialization:
      fail_on_empty_beans: false

management:
  endpoint:
    mappings:
      enabled: true

destinations:
  queues:
    MATCH:
      exchange: match
      routing-key: MATCH
